/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import HomeLayout from "@/layouts/home-layout/index.vue";
import AppLayout from "@/layouts/app-layout/index.vue";
import CenterLayout from "@/layouts/center-layout/index.vue";
import BackendLayout from "@/layouts/backend-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  home: HomeLayout,
  app: AppLayout,
  center: CenterLayout,
  backend: BackendLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  init: () => import("@/views/_builtin/init/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  mbinput: () => import("@/views/_builtin/mbinput/index.vue"),
  app_dashboard: () => import("@/views/app/dashboard/[id].vue"),
  "app_flow-handle": () => import("@/views/app/flow-handle/[id].vue"),
  "app_flow-received": () => import("@/views/app/flow-received/[id].vue"),
  "app_flow-start": () => import("@/views/app/flow-start/[id].vue"),
  "app_flow-started": () => import("@/views/app/flow-started/[id].vue"),
  "app_flow-todo": () => import("@/views/app/flow-todo/[id].vue"),
  app_init: () => import("@/views/app/init/[id].vue"),
  app_module: () => import("@/views/app/module/[id].vue"),
  "backend_app_form-import": () => import("@/views/backend/app/form-import/[id].vue"),
  "backend_data_data-etl": () => import("@/views/backend/data/data-etl/[id].vue"),
  "backend_data_data-view": () => import("@/views/backend/data/data-view/[id].vue"),
  center_enterprise_base_entinfo: () => import("@/views/center/enterprise/base_entinfo/index.vue"),
  center_enterprise_base_verinfo: () => import("@/views/center/enterprise/base_verinfo/index.vue"),
  center_enterprise_perm_admin: () => import("@/views/center/enterprise/perm_admin/index.vue"),
  center_enterprise_perm_group: () => import("@/views/center/enterprise/perm_group/index.vue"),
  center_enterprise_system_del: () => import("@/views/center/enterprise/system_del/index.vue"),
  center_enterprise_system_ent: () => import("@/views/center/enterprise/system_ent/index.vue"),
  center_enterprise_system_log: () => import("@/views/center/enterprise/system_log/index.vue"),
  center_enterprise_system_msg: () => import("@/views/center/enterprise/system_msg/index.vue"),
  center_enterprise_system_report: () => import("@/views/center/enterprise/system_report/index.vue"),
  center_enterprise_users_external: () => import("@/views/center/enterprise/users_external/index.vue"),
  center_enterprise_users_internal: () => import("@/views/center/enterprise/users_internal/index.vue"),
  center_messages: () => import("@/views/center/messages/index.vue"),
  center_mycenter: () => import("@/views/center/mycenter/index.vue"),
  center_workbench: () => import("@/views/center/workbench/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
