/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'app',
    path: '/app',
    component: 'layout.app',
    meta: {
      title: 'app',
      icon: 'fluent--book-information-24-regular',
      i18nKey: 'route.app'
    },
    children: [
      {
        name: 'app_dashboard',
        path: '/app/dashboard/:id',
        component: 'view.app_dashboard',
        meta: {
          title: 'app_dashboard',
          i18nKey: 'route.app_dashboard'
        }
      },
      {
        name: 'app_flow-handle',
        path: '/app/flow-handle/:id',
        component: 'view.app_flow-handle',
        meta: {
          title: 'app_flow-handle',
          i18nKey: 'route.app_flow-handle',
          icon: 'fluent--task-list-square-rtl-24-filled'
        }
      },
      {
        name: 'app_flow-received',
        path: '/app/flow-received/:id',
        component: 'view.app_flow-received',
        meta: {
          title: 'app_flow-received',
          i18nKey: 'route.app_flow-received',
          icon: 'mdi:clipboard-text-clock'
        }
      },
      {
        name: 'app_flow-start',
        path: '/app/flow-start/:id',
        component: 'view.app_flow-start',
        meta: {
          title: 'app_flow-start',
          i18nKey: 'route.app_flow-start',
          icon: 'fluent--play-circle-24-filled'
        }
      },
      {
        name: 'app_flow-started',
        path: '/app/flow-started/:id',
        component: 'view.app_flow-started',
        meta: {
          title: 'app_flow-started',
          i18nKey: 'route.app_flow-started',
          icon: 'fluent--send-24-filled'
        }
      },
      {
        name: 'app_flow-todo',
        path: '/app/flow-todo/:id',
        component: 'view.app_flow-todo',
        meta: {
          title: 'app_flow-todo',
          i18nKey: 'route.app_flow-todo',
          icon: 'lets-icons--sign-in-squre-fill'
        }
      },
      {
        name: 'app_init',
        path: '/app/init/:id',
        component: 'view.app_init',
        meta: {
          title: 'app_init',
          i18nKey: 'route.app_init'
        }
      },
      {
        name: 'app_module',
        path: '/app/module/:id',
        component: 'view.app_module',
        meta: {
          title: 'app_module',
          i18nKey: 'route.app_module'
        }
      }
    ]
  },
  {
    name: 'backend',
    path: '/backend',
    component: 'layout.backend',
    meta: {
      title: 'backend',
      i18nKey: 'route.backend'
    },
    children: [
      {
        name: 'backend_app',
        path: '/backend/app',
        meta: {
          title: 'backend_app',
          i18nKey: 'route.backend_app',
          icon: 'mdi:application-cog-outline'
        },
        children: [
          {
            name: 'backend_app_form-import',
            path: '/backend/app/form-import/:id',
            component: 'view.backend_app_form-import',
            meta: {
              title: 'backend_app_form-import',
              i18nKey: 'route.backend_app_form-import',
              icon: 'mdi:import'
            }
          }
        ]
      },
      {
        name: 'backend_data',
        path: '/backend/data',
        meta: {
          title: 'backend_data',
          i18nKey: 'route.backend_data',
          icon: 'mdi:database-cog-outline'
        },
        children: [
          {
            name: 'backend_data_data-etl',
            path: '/backend/data/data-etl/:id',
            component: 'view.backend_data_data-etl',
            meta: {
              title: 'backend_data_data-etl',
              i18nKey: 'route.backend_data_data-etl',
              icon: 'carbon--data-refinery',
              order: 1
            }
          },
          {
            name: 'backend_data_data-view',
            path: '/backend/data/data-view/:id',
            component: 'view.backend_data_data-view',
            meta: {
              title: 'backend_data_data-view',
              i18nKey: 'route.backend_data_data-view',
              icon: 'carbon--data-base-alt',
              order: 0
            }
          }
        ]
      }
    ]
  },
  {
    name: 'center',
    path: '/center',
    component: 'layout.center',
    meta: {
      title: 'center',
      i18nKey: 'route.center'
    },
    children: [
      {
        name: 'center_enterprise',
        path: '/center/enterprise',
        meta: {
          title: 'center_enterprise',
          i18nKey: 'route.center_enterprise'
        },
        children: [
          {
            name: 'center_enterprise_base',
            path: '/center/enterprise/base',
            meta: {
              title: 'center_enterprise_base',
              icon: '',
              i18nKey: 'route.center_enterprise_base',
              order: 0
            },
            children: [
              {
                name: 'center_enterprise_base_entinfo',
                path: '/center/enterprise/base/entinfo',
                component: 'view.center_enterprise_base_entinfo',
                meta: {
                  title: 'center_enterprise_base_entinfo',
                  icon: 'heroicons-outline--office-building',
                  i18nKey: 'route.center_enterprise_base_entinfo'
                }
              },
              {
                name: 'center_enterprise_base_verinfo',
                path: '/center/enterprise/base/verinfo',
                component: 'view.center_enterprise_base_verinfo',
                meta: {
                  title: 'center_enterprise_base_verinfo',
                  icon: 'mingcute--version-line',
                  i18nKey: 'route.center_enterprise_base_verinfo'
                }
              }
            ]
          },
          {
            name: 'center_enterprise_perm',
            path: '/center/enterprise/perm',
            meta: {
              title: 'center_enterprise_perm',
              icon: '',
              i18nKey: 'route.center_enterprise_perm',
              order: 2
            },
            children: [
              {
                name: 'center_enterprise_perm_admin',
                path: '/center/enterprise/perm/admin',
                component: 'view.center_enterprise_perm_admin',
                meta: {
                  title: 'center_enterprise_perm_admin',
                  icon: 'mdi:account-cog-outline',
                  i18nKey: 'route.center_enterprise_perm_admin'
                }
              },
              {
                name: 'center_enterprise_perm_group',
                path: '/center/enterprise/perm/group',
                component: 'view.center_enterprise_perm_group',
                meta: {
                  title: 'center_enterprise_perm_group',
                  icon: 'material-symbols--fact-check-outline-rounded',
                  i18nKey: 'route.center_enterprise_perm_group'
                }
              }
            ]
          },
          {
            name: 'center_enterprise_system',
            path: '/center/enterprise/system',
            meta: {
              title: 'center_enterprise_system',
              icon: '',
              i18nKey: 'route.center_enterprise_system',
              order: 3
            },
            children: [
              {
                name: 'center_enterprise_system_del',
                path: '/center/enterprise/system/del',
                component: 'view.center_enterprise_system_del',
                meta: {
                  title: 'center_enterprise_system_del',
                  icon: 'mdi:trash-can-outline',
                  i18nKey: 'route.center_enterprise_system_del',
                  order: 6
                }
              },
              {
                name: 'center_enterprise_system_ent',
                path: '/center/enterprise/system/ent',
                component: 'view.center_enterprise_system_ent',
                meta: {
                  title: 'center_enterprise_system_ent',
                  icon: 'tabler--building-cog',
                  i18nKey: 'route.center_enterprise_system_ent',
                  order: 1
                }
              },
              {
                name: 'center_enterprise_system_log',
                path: '/center/enterprise/system/log',
                component: 'view.center_enterprise_system_log',
                meta: {
                  title: 'center_enterprise_system_log',
                  icon: 'tabler--clipboard-list',
                  i18nKey: 'route.center_enterprise_system_log',
                  order: 5
                }
              },
              {
                name: 'center_enterprise_system_msg',
                path: '/center/enterprise/system/msg',
                component: 'view.center_enterprise_system_msg',
                meta: {
                  title: 'center_enterprise_system_msg',
                  icon: 'lets-icons--message',
                  i18nKey: 'route.center_enterprise_system_msg',
                  order: 3
                }
              },
              {
                name: 'center_enterprise_system_report',
                path: '/center/enterprise/system/report',
                component: 'view.center_enterprise_system_report',
                meta: {
                  title: 'center_enterprise_system_report',
                  icon: 'tabler--report-analytics',
                  i18nKey: 'route.center_enterprise_system_report',
                  order: 4
                }
              }
            ]
          },
          {
            name: 'center_enterprise_users',
            path: '/center/enterprise/users',
            meta: {
              title: 'center_enterprise_users',
              icon: '',
              i18nKey: 'route.center_enterprise_users',
              order: 1
            },
            children: [
              {
                name: 'center_enterprise_users_external',
                path: '/center/enterprise/users/external',
                component: 'view.center_enterprise_users_external',
                meta: {
                  title: 'center_enterprise_users_external',
                  icon: 'codicon--organization',
                  i18nKey: 'route.center_enterprise_users_external',
                  order: 1
                }
              },
              {
                name: 'center_enterprise_users_internal',
                path: '/center/enterprise/users/internal',
                component: 'view.center_enterprise_users_internal',
                meta: {
                  title: 'center_enterprise_users_internal',
                  icon: 'fluent-mdl2--org',
                  i18nKey: 'route.center_enterprise_users_internal',
                  order: 0
                }
              }
            ]
          }
        ]
      },
      {
        name: 'center_messages',
        path: '/center/messages',
        component: 'view.center_messages',
        meta: {
          title: 'center_messages',
          i18nKey: 'route.center_messages'
        }
      },
      {
        name: 'center_mycenter',
        path: '/center/mycenter',
        component: 'view.center_mycenter',
        meta: {
          title: 'center_mycenter',
          i18nKey: 'route.center_mycenter'
        }
      },
      {
        name: 'center_workbench',
        path: '/center/workbench',
        component: 'view.center_workbench',
        meta: {
          title: 'center_workbench',
          i18nKey: 'route.center_workbench'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.home$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'init',
    path: '/init',
    component: 'layout.blank$view.init',
    meta: {
      title: 'init',
      i18nKey: 'route.init',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'mbinput',
    path: '/mbinput',
    component: 'layout.blank$view.mbinput',
    meta: {
      title: 'mbinput',
      i18nKey: 'route.mbinput',
      constant: true,
      hideInMenu: true
    }
  }
];
